CREATE TABLE IF NOT EXISTS Allergens (
    AllergenID INTEGER,
    AllergenType TEXT,
    PRIMARY KEY (AllergenID)
);
insert into Allergens (AllergenID, AllergenType) values (654, 'Pastry - Mini French Pastries');
insert into Allergens (AllergenID, AllergenType) values (836, 'Pastry - Chocolate Chip Muffin');
insert into Allergens (AllergenID, AllergenType) values (658, 'Wine - Jaboulet Cotes Du Rhone');
insert into Allergens (AllergenID, AllergenType) values (667, 'Salt - Sea');
insert into Allergens (AllergenID, AllergenType) values (711, 'Pork - Loin, Bone - In');
insert into Allergens (AllergenID, AllergenType) values (106, 'Straw - Regular');
insert into Allergens (AllergenID, AllergenType) values (583, 'Wine - Vineland Estate Semi - Dry');
insert into Allergens (AllergenID, AllergenType) values (524, 'Ecolab - Ster Bac');
insert into Allergens (AllergenID, AllergenType) values (552, 'Beef - Ox Tongue');
insert into Allergens (AllergenID, AllergenType) values (902, 'Fennel');
insert into Allergens (AllergenID, AllergenType) values (642, 'Bread Crumbs - Japanese Style');
insert into Allergens (AllergenID, AllergenType) values (563, 'Coffee Cup 8oz 5338cd');
insert into Allergens (AllergenID, AllergenType) values (686, 'Table Cloth 53x69 White');
insert into Allergens (AllergenID, AllergenType) values (548, 'Wine - Maipo Valle Cabernet');
insert into Allergens (AllergenID, AllergenType) values (108, 'Galliano');
insert into Allergens (AllergenID, AllergenType) values (775, 'Pastry - Trippleberry Muffin - Mini');
insert into Allergens (AllergenID, AllergenType) values (936, 'Truffle - Whole Black Peeled');
insert into Allergens (AllergenID, AllergenType) values (143, 'Apricots Fresh');
insert into Allergens (AllergenID, AllergenType) values (985, 'Chips - Potato Jalapeno');
insert into Allergens (AllergenID, AllergenType) values (656, 'Swordfish Loin Portions');
insert into Allergens (AllergenID, AllergenType) values (840, 'Cheese - Romano, Grated');
insert into Allergens (AllergenID, AllergenType) values (672, 'Chicken - Tenderloin');
insert into Allergens (AllergenID, AllergenType) values (561, 'Wine - Vidal Icewine Magnotta');
insert into Allergens (AllergenID, AllergenType) values (280, 'Oil - Grapeseed Oil');
insert into Allergens (AllergenID, AllergenType) values (583, 'Pepper - Sorrano');
insert into Allergens (AllergenID, AllergenType) values (626, 'Tequila - Sauza Silver');
insert into Allergens (AllergenID, AllergenType) values (875, 'Sesame Seed Black');
insert into Allergens (AllergenID, AllergenType) values (453, 'Squid - Tubes / Tenticles 10/20');
insert into Allergens (AllergenID, AllergenType) values (784, 'Soup - French Onion, Dry');
insert into Allergens (AllergenID, AllergenType) values (327, 'Soup - Campbells, Lentil');
insert into Allergens (AllergenID, AllergenType) values (785, 'Sugar Thermometer');
insert into Allergens (AllergenID, AllergenType) values (914, 'Veal - Liver');
insert into Allergens (AllergenID, AllergenType) values (272, 'Wine - Balbach Riverside');
insert into Allergens (AllergenID, AllergenType) values (981, 'Marjoram - Fresh');
insert into Allergens (AllergenID, AllergenType) values (586, 'Oregano - Dry, Rubbed');
insert into Allergens (AllergenID, AllergenType) values (981, 'Soup Campbells - Italian Wedding');
insert into Allergens (AllergenID, AllergenType) values (793, 'Sherbet - Raspberry');
insert into Allergens (AllergenID, AllergenType) values (833, 'Bread - Rye');
insert into Allergens (AllergenID, AllergenType) values (961, 'Juice - Apple Cider');
insert into Allergens (AllergenID, AllergenType) values (914, 'Juice - V8, Tomato');
insert into Allergens (AllergenID, AllergenType) values (598, 'Cheese - Pied De Vents');
insert into Allergens (AllergenID, AllergenType) values (815, 'Lamb - Racks, Frenched');
insert into Allergens (AllergenID, AllergenType) values (448, 'Crush - Grape, 355 Ml');
insert into Allergens (AllergenID, AllergenType) values (538, 'Bar Mix - Lemon');
insert into Allergens (AllergenID, AllergenType) values (998, 'Cabbage - Green');
insert into Allergens (AllergenID, AllergenType) values (943, 'Veal - Osso Bucco');
insert into Allergens (AllergenID, AllergenType) values (943, 'Muffin Mix - Morning Glory');
insert into Allergens (AllergenID, AllergenType) values (957, 'Water - Mineral, Natural');
insert into Allergens (AllergenID, AllergenType) values (254, 'Temperature Recording Station');
insert into Allergens (AllergenID, AllergenType) values (661, 'Crab - Claws, Snow 16 - 24');
insert into Allergens (AllergenID, AllergenType) values (990, 'Wine - Jafflin Bourgongone');
insert into Allergens (AllergenID, AllergenType) values (498, 'Bread - Onion Focaccia');
insert into Allergens (AllergenID, AllergenType) values (130, 'Soup - Knorr, Chicken Noodle');
insert into Allergens (AllergenID, AllergenType) values (302, 'Maple Syrup');
insert into Allergens (AllergenID, AllergenType) values (792, 'Schnappes Peppermint - Walker');
insert into Allergens (AllergenID, AllergenType) values (1000, 'Soup - Campbells Beef Strogonoff');
insert into Allergens (AllergenID, AllergenType) values (423, 'Squeeze Bottle');
insert into Allergens (AllergenID, AllergenType) values (393, 'Foam Tray S2');
insert into Allergens (AllergenID, AllergenType) values (148, 'Beans - Long, Chinese');
insert into Allergens (AllergenID, AllergenType) values (938, 'Anchovy Fillets');
insert into Allergens (AllergenID, AllergenType) values (528, 'Hinge W Undercut');
insert into Allergens (AllergenID, AllergenType) values (518, 'Cheese - Brie, Triple Creme');
insert into Allergens (AllergenID, AllergenType) values (304, 'Apples - Sliced / Wedge');
insert into Allergens (AllergenID, AllergenType) values (281, 'Parasol Pick Stir Stick');
insert into Allergens (AllergenID, AllergenType) values (601, 'Wine - Saint Emilion Calvet');
insert into Allergens (AllergenID, AllergenType) values (499, 'Olives - Morracan Dired');
insert into Allergens (AllergenID, AllergenType) values (863, 'Energy Drink Bawls');
insert into Allergens (AllergenID, AllergenType) values (290, 'Mushroom - Enoki, Fresh');
insert into Allergens (AllergenID, AllergenType) values (662, 'Bread - Granary Small Pull');
insert into Allergens (AllergenID, AllergenType) values (393, 'Silicone Paper 16.5x24');
insert into Allergens (AllergenID, AllergenType) values (828, 'Curry Powder');
insert into Allergens (AllergenID, AllergenType) values (434, 'Wine - White, Gewurtzraminer');
insert into Allergens (AllergenID, AllergenType) values (168, 'Tuna - Bluefin');
insert into Allergens (AllergenID, AllergenType) values (484, 'Allspice - Jamaican');
insert into Allergens (AllergenID, AllergenType) values (675, 'Shrimp - Tiger 21/25');
insert into Allergens (AllergenID, AllergenType) values (573, 'Crackers - Melba Toast');
insert into Allergens (AllergenID, AllergenType) values (200, 'Silicone Parch. 16.3x24.3');
insert into Allergens (AllergenID, AllergenType) values (458, 'Glucose');
insert into Allergens (AllergenID, AllergenType) values (444, 'Sugar - Sweet N Low, Individual');
insert into Allergens (AllergenID, AllergenType) values (490, 'Lettuce - Radicchio');
insert into Allergens (AllergenID, AllergenType) values (786, 'Beans - Black Bean, Canned');
insert into Allergens (AllergenID, AllergenType) values (410, 'Appetizer - Shrimp Puff');
insert into Allergens (AllergenID, AllergenType) values (417, 'Bread Base - Toscano');
insert into Allergens (AllergenID, AllergenType) values (669, 'Island Oasis - Raspberry');
insert into Allergens (AllergenID, AllergenType) values (777, 'Guinea Fowl');
insert into Allergens (AllergenID, AllergenType) values (904, 'Corn - On The Cob');
insert into Allergens (AllergenID, AllergenType) values (839, 'Pepper - Green');
insert into Allergens (AllergenID, AllergenType) values (762, 'Veal - Insides Provini');
insert into Allergens (AllergenID, AllergenType) values (951, 'Bread Country Roll');
insert into Allergens (AllergenID, AllergenType) values (674, 'Wine - Masi Valpolocell');
