CREATE TABLE IF NOT EXISTS Meals (
    MealID INTEGER,
    MealName TEXT,
    ServedAt INTEGER,
    Description TEXT,
    Votes INTEGER,
    Allergen INTEGER,
    DietaryConstraints INTEGER,
    Macros INTEGER,
    PRIMARY KEY (MealID),
    FOREIGN KEY (ServedAt) REFERENCES DiningHall(HallID),
    FOREIGN KEY (Votes) REFERENCES Votes(VoteID),
    FOREIGN KEY (Allergen) REFERENCES Allergens(AllergenID),
    FOREIGN KEY (DietaryConstraints) REFERENCES DietaryRestrictions(ConstraintID),
    FOREIGN KEY (Macros) REFERENCES Macros(MacroID)
);
insert into Meals (MealID, MealName, ServedAt, Description, Votes, Allergen, DietaryConstraints, Macros) values (391, 'Puree - Kiwi', 490, 'Nullam varius. Nulla facilisi.', 260, 145, 1, 388);
insert into Meals (MealID, MealName, ServedAt, Description, Votes, Allergen, DietaryConstraints, Macros) values (176, 'Kiwano', 250, 'Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros. Vestibulum ac est lacinia nisi venenatis tristique. Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue.', 265, 778, 3, 161);
insert into Meals (MealID, MealName, ServedAt, Description, Votes, Allergen, DietaryConstraints, Macros) values (460, 'Sauce - Hollandaise', 689, 'Donec ut mauris eget massa tempor convallis.', 203, 228, 4, 915);
insert into Meals (MealID, MealName, ServedAt, Description, Votes, Allergen, DietaryConstraints, Macros) values (366, 'Pail For Lid 1537', 787, 'Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Etiam vel augue.', 111, 936, 2, 202);
insert into Meals (MealID, MealName, ServedAt, Description, Votes, Allergen, DietaryConstraints, Macros) values (219, 'Flour - All Purpose', 436, 'Curabitur at ipsum ac tellus semper interdum. Mauris ullamcorper purus sit amet nulla.', 144, 618, 4, 584);
insert into Meals (MealID, MealName, ServedAt, Description, Votes, Allergen, DietaryConstraints, Macros) values (374, 'Milk - Buttermilk', 441, 'Mauris lacinia sapien quis libero. Nullam sit amet turpis elementum ligula vehicula consequat.', 120, 410, 3, 351);
insert into Meals (MealID, MealName, ServedAt, Description, Votes, Allergen, DietaryConstraints, Macros) values (592, 'Cheese - Comtomme', 734, 'Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh.', 267, 967, 2, 820);
insert into Meals (MealID, MealName, ServedAt, Description, Votes, Allergen, DietaryConstraints, Macros) values (176, 'Corn Shoots', 689, 'Morbi vel lectus in quam fringilla rhoncus. Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis.', 300, 571, 4, 351);
insert into Meals (MealID, MealName, ServedAt, Description, Votes, Allergen, DietaryConstraints, Macros) values (245, 'Island Oasis - Strawberry', 281, 'Nunc purus. Phasellus in felis.', 126, 547, 4, 696);
insert into Meals (MealID, MealName, ServedAt, Description, Votes, Allergen, DietaryConstraints, Macros) values (997, 'Spice - Pepper Portions', 846, 'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi. Integer ac neque.', 124, 835, 4, 314);
insert into Meals (MealID, MealName, ServedAt, Description, Votes, Allergen, DietaryConstraints, Macros) values (804, 'Wine - White, French Cross', 252, 'Nullam varius. Nulla facilisi.', 94, 578, 3, 505);
insert into Meals (MealID, MealName, ServedAt, Description, Votes, Allergen, DietaryConstraints, Macros) values (671, 'Chilli Paste, Ginger Garlic', 862, 'Cras in purus eu magna vulputate luctus. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.', 106, 466, 4, 476);
insert into Meals (MealID, MealName, ServedAt, Description, Votes, Allergen, DietaryConstraints, Macros) values (828, 'Ezy Change Mophandle', 455, 'Aliquam quis turpis eget elit sodales scelerisque. Mauris sit amet eros.', 213, 269, 1, 136);
insert into Meals (MealID, MealName, ServedAt, Description, Votes, Allergen, DietaryConstraints, Macros) values (388, 'Chef Hat 25cm', 785, 'Morbi a ipsum. Integer a nibh. In quis justo.', 287, 521, 1, 327);
insert into Meals (MealID, MealName, ServedAt, Description, Votes, Allergen, DietaryConstraints, Macros) values (496, 'Bowl 12 Oz - Showcase 92012', 487, 'Aenean lectus. Pellentesque eget nunc. Donec quis orci eget orci vehicula condimentum.', 76, 448, 4, 436);
insert into Meals (MealID, MealName, ServedAt, Description, Votes, Allergen, DietaryConstraints, Macros) values (148, 'Soap - Pine Sol Floor Cleaner', 147, 'Sed sagittis. Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci.', 172, 953, 1, 940);
insert into Meals (MealID, MealName, ServedAt, Description, Votes, Allergen, DietaryConstraints, Macros) values (493, 'Chocolate Liqueur - Godet White', 358, 'Morbi ut odio.', 163, 239, 5, 532);
insert into Meals (MealID, MealName, ServedAt, Description, Votes, Allergen, DietaryConstraints, Macros) values (323, 'Radish - Black, Winter, Organic', 554, 'Aenean fermentum. Donec ut mauris eget massa tempor convallis. Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh.', 165, 837, 3, 495);
insert into Meals (MealID, MealName, ServedAt, Description, Votes, Allergen, DietaryConstraints, Macros) values (886, 'Wine - Chianti Classica Docg', 990, 'Mauris lacinia sapien quis libero. Nullam sit amet turpis elementum ligula vehicula consequat.', 291, 260, 1, 939);
insert into Meals (MealID, MealName, ServedAt, Description, Votes, Allergen, DietaryConstraints, Macros) values (650, 'Wasabi Paste', 441, 'Cras in purus eu magna vulputate luctus. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vivamus vestibulum sagittis sapien.', 247, 803, 5, 648);
insert into Meals (MealID, MealName, ServedAt, Description, Votes, Allergen, DietaryConstraints, Macros) values (562, 'Wine - Chateau Aqueria Tavel', 338, 'Nullam sit amet turpis elementum ligula vehicula consequat. Morbi a ipsum.', 9, 120, 1, 674);
insert into Meals (MealID, MealName, ServedAt, Description, Votes, Allergen, DietaryConstraints, Macros) values (835, 'Cake Circle, Foil, Scallop', 368, 'In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem. Duis aliquam convallis nunc. Proin at turpis a pede posuere nonummy.', 223, 781, 4, 983);
insert into Meals (MealID, MealName, ServedAt, Description, Votes, Allergen, DietaryConstraints, Macros) values (416, 'Beef - Bones, Marrow', 896, 'Duis at velit eu est congue elementum.', 7, 816, 2, 1000);
insert into Meals (MealID, MealName, ServedAt, Description, Votes, Allergen, DietaryConstraints, Macros) values (382, 'Cardamon Ground', 529, 'Aliquam erat volutpat. In congue.', 27, 589, 4, 201);
insert into Meals (MealID, MealName, ServedAt, Description, Votes, Allergen, DietaryConstraints, Macros) values (725, 'Pastry - Choclate Baked', 764, 'Nam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla.', 157, 147, 3, 721);
insert into Meals (MealID, MealName, ServedAt, Description, Votes, Allergen, DietaryConstraints, Macros) values (301, 'Tobasco Sauce', 214, 'Nulla justo.', 62, 268, 5, 136);
insert into Meals (MealID, MealName, ServedAt, Description, Votes, Allergen, DietaryConstraints, Macros) values (921, 'Puree - Mango', 452, 'Proin risus. Praesent lectus.', 265, 508, 2, 665);
insert into Meals (MealID, MealName, ServedAt, Description, Votes, Allergen, DietaryConstraints, Macros) values (631, 'Wine - Muscadet Sur Lie', 421, 'Vivamus vestibulum sagittis sapien. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Etiam vel augue.', 181, 995, 3, 808);
insert into Meals (MealID, MealName, ServedAt, Description, Votes, Allergen, DietaryConstraints, Macros) values (200, 'Steampan Lid', 345, 'Nam dui.', 60, 255, 5, 872);
insert into Meals (MealID, MealName, ServedAt, Description, Votes, Allergen, DietaryConstraints, Macros) values (208, 'Juice - Mango', 414, 'In hac habitasse platea dictumst. Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante.', 292, 283, 3, 694);
insert into Meals (MealID, MealName, ServedAt, Description, Votes, Allergen, DietaryConstraints, Macros) values (967, 'Snapple - Mango Maddness', 266, 'Donec ut mauris eget massa tempor convallis.', 284, 922, 4, 159);
insert into Meals (MealID, MealName, ServedAt, Description, Votes, Allergen, DietaryConstraints, Macros) values (422, 'Shiro Miso', 551, 'Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla. Nunc purus.', 252, 770, 1, 393);
insert into Meals (MealID, MealName, ServedAt, Description, Votes, Allergen, DietaryConstraints, Macros) values (105, 'Pears - Fiorelle', 457, 'Integer ac leo.', 298, 839, 4, 755);
insert into Meals (MealID, MealName, ServedAt, Description, Votes, Allergen, DietaryConstraints, Macros) values (796, 'Sprite, Diet - 355ml', 555, 'Donec ut dolor.', 24, 725, 3, 914);
insert into Meals (MealID, MealName, ServedAt, Description, Votes, Allergen, DietaryConstraints, Macros) values (768, 'Wine - Taylors Reserve', 356, 'In eleifend quam a odio.', 100, 712, 1, 638);
insert into Meals (MealID, MealName, ServedAt, Description, Votes, Allergen, DietaryConstraints, Macros) values (976, 'Chips - Assorted', 353, 'Curabitur convallis. Duis consequat dui nec nisi volutpat eleifend.', 238, 469, 4, 538);
insert into Meals (MealID, MealName, ServedAt, Description, Votes, Allergen, DietaryConstraints, Macros) values (182, 'Island Oasis - Magarita Mix', 392, 'Integer ac leo.', 19, 961, 2, 213);
insert into Meals (MealID, MealName, ServedAt, Description, Votes, Allergen, DietaryConstraints, Macros) values (573, 'Pail - 15l White, With Handle', 281, 'Morbi quis tortor id nulla ultrices aliquet. Maecenas leo odio, condimentum id, luctus nec, molestie sed, justo.', 142, 469, 2, 564);
insert into Meals (MealID, MealName, ServedAt, Description, Votes, Allergen, DietaryConstraints, Macros) values (183, 'Mushroom - Crimini', 266, 'Nulla suscipit ligula in lacus. Curabitur at ipsum ac tellus semper interdum. Mauris ullamcorper purus sit amet nulla.', 224, 517, 3, 403);
insert into Meals (MealID, MealName, ServedAt, Description, Votes, Allergen, DietaryConstraints, Macros) values (809, 'Eggroll', 158, 'Curabitur at ipsum ac tellus semper interdum. Mauris ullamcorper purus sit amet nulla.', 153, 425, 3, 548);
insert into Meals (MealID, MealName, ServedAt, Description, Votes, Allergen, DietaryConstraints, Macros) values (217, 'Wine - Chianti Classica Docg', 653, 'Suspendisse ornare consequat lectus.', 194, 824, 1, 518);
insert into Meals (MealID, MealName, ServedAt, Description, Votes, Allergen, DietaryConstraints, Macros) values (105, 'Gingerale - Diet - Schweppes', 227, 'Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci. Mauris lacinia sapien quis libero. Nullam sit amet turpis elementum ligula vehicula consequat.', 105, 480, 3, 605);
insert into Meals (MealID, MealName, ServedAt, Description, Votes, Allergen, DietaryConstraints, Macros) values (966, 'Venison - Liver', 412, 'Morbi non quam nec dui luctus rutrum.', 264, 499, 2, 989);
insert into Meals (MealID, MealName, ServedAt, Description, Votes, Allergen, DietaryConstraints, Macros) values (533, 'Star Fruit', 872, 'Duis ac nibh.', 90, 839, 5, 867);
insert into Meals (MealID, MealName, ServedAt, Description, Votes, Allergen, DietaryConstraints, Macros) values (174, 'Cup - Translucent 7 Oz Clear', 769, 'Donec dapibus. Duis at velit eu est congue elementum. In hac habitasse platea dictumst.', 4, 431, 3, 163);
insert into Meals (MealID, MealName, ServedAt, Description, Votes, Allergen, DietaryConstraints, Macros) values (448, 'Broom And Broom Rack White', 390, 'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est. Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros. Vestibulum ac est lacinia nisi venenatis tristique.', 22, 122, 3, 252);
insert into Meals (MealID, MealName, ServedAt, Description, Votes, Allergen, DietaryConstraints, Macros) values (127, 'Dragon Fruit', 321, 'Nunc nisl. Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa.', 19, 674, 5, 713);
insert into Meals (MealID, MealName, ServedAt, Description, Votes, Allergen, DietaryConstraints, Macros) values (727, 'Crackers - Graham', 472, 'Nunc rhoncus dui vel sem.', 135, 758, 1, 176);
insert into Meals (MealID, MealName, ServedAt, Description, Votes, Allergen, DietaryConstraints, Macros) values (966, 'Vodka - Smirnoff', 723, 'Nunc nisl. Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa. Donec dapibus.', 118, 473, 3, 159);
insert into Meals (MealID, MealName, ServedAt, Description, Votes, Allergen, DietaryConstraints, Macros) values (998, 'Foil - Round Foil', 679, 'Donec dapibus. Duis at velit eu est congue elementum.', 1, 154, 1, 684);
insert into Meals (MealID, MealName, ServedAt, Description, Votes, Allergen, DietaryConstraints, Macros) values (705, 'Graham Cracker Mix', 885, 'Nulla ut erat id mauris vulputate elementum. Nullam varius. Nulla facilisi.', 22, 997, 2, 726);
insert into Meals (MealID, MealName, ServedAt, Description, Votes, Allergen, DietaryConstraints, Macros) values (584, 'Syrup - Pancake', 146, 'Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo. In blandit ultrices enim. Lorem ipsum dolor sit amet, consectetuer adipiscing elit.', 18, 216, 5, 849);
insert into Meals (MealID, MealName, ServedAt, Description, Votes, Allergen, DietaryConstraints, Macros) values (341, 'Appetizer - Asian Shrimp Roll', 108, 'Integer ac leo. Pellentesque ultrices mattis odio.', 91, 128, 4, 940);
insert into Meals (MealID, MealName, ServedAt, Description, Votes, Allergen, DietaryConstraints, Macros) values (138, 'Squash - Pepper', 238, 'Maecenas rhoncus aliquam lacus.', 243, 867, 4, 702);
insert into Meals (MealID, MealName, ServedAt, Description, Votes, Allergen, DietaryConstraints, Macros) values (582, 'Horseradish - Prepared', 968, 'Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa. Donec dapibus.', 110, 295, 4, 984);
insert into Meals (MealID, MealName, ServedAt, Description, Votes, Allergen, DietaryConstraints, Macros) values (980, 'Lamb Rack Frenched Australian', 984, 'Vestibulum sed magna at nunc commodo placerat. Praesent blandit.', 170, 420, 2, 923);
insert into Meals (MealID, MealName, ServedAt, Description, Votes, Allergen, DietaryConstraints, Macros) values (777, 'Sugar - Sweet N Low, Individual', 873, 'Integer tincidunt ante vel ipsum.', 218, 497, 2, 872);
insert into Meals (MealID, MealName, ServedAt, Description, Votes, Allergen, DietaryConstraints, Macros) values (774, 'Everfresh Products', 949, 'Nam tristique tortor eu pede.', 36, 112, 3, 687);
insert into Meals (MealID, MealName, ServedAt, Description, Votes, Allergen, DietaryConstraints, Macros) values (162, 'Curry Powder', 631, 'Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci. Mauris lacinia sapien quis libero. Nullam sit amet turpis elementum ligula vehicula consequat.', 256, 201, 5, 192);
insert into Meals (MealID, MealName, ServedAt, Description, Votes, Allergen, DietaryConstraints, Macros) values (983, 'Pimento - Canned', 199, 'Nulla suscipit ligula in lacus. Curabitur at ipsum ac tellus semper interdum.', 17, 481, 3, 160);
insert into Meals (MealID, MealName, ServedAt, Description, Votes, Allergen, DietaryConstraints, Macros) values (124, 'Beans - Fine', 515, 'Sed accumsan felis. Ut at dolor quis odio consequat varius.', 162, 311, 4, 838);
insert into Meals (MealID, MealName, ServedAt, Description, Votes, Allergen, DietaryConstraints, Macros) values (915, 'Langers - Ruby Red Grapfruit', 592, 'Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis.', 77, 185, 4, 794);
insert into Meals (MealID, MealName, ServedAt, Description, Votes, Allergen, DietaryConstraints, Macros) values (837, 'Cake Circle, Foil, Scallop', 749, 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Proin interdum mauris non ligula pellentesque ultrices.', 274, 792, 4, 717);
insert into Meals (MealID, MealName, ServedAt, Description, Votes, Allergen, DietaryConstraints, Macros) values (889, 'Soup - Campbells Chili', 947, 'Quisque ut erat. Curabitur gravida nisi at nibh. In hac habitasse platea dictumst.', 257, 794, 2, 800);
insert into Meals (MealID, MealName, ServedAt, Description, Votes, Allergen, DietaryConstraints, Macros) values (823, 'Peppercorns - Pink', 134, 'Nulla facilisi.', 67, 873, 4, 811);
insert into Meals (MealID, MealName, ServedAt, Description, Votes, Allergen, DietaryConstraints, Macros) values (889, 'Melon - Cantaloupe', 472, 'Morbi ut odio. Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo.', 100, 119, 2, 596);
insert into Meals (MealID, MealName, ServedAt, Description, Votes, Allergen, DietaryConstraints, Macros) values (452, 'Foam Cup 6 Oz', 394, 'Nullam porttitor lacus at turpis. Donec posuere metus vitae ipsum. Aliquam non mauris.', 187, 836, 3, 652);
insert into Meals (MealID, MealName, ServedAt, Description, Votes, Allergen, DietaryConstraints, Macros) values (604, 'Pepper - Gypsy Pepper', 476, 'Morbi porttitor lorem id ligula.', 61, 571, 3, 216);
insert into Meals (MealID, MealName, ServedAt, Description, Votes, Allergen, DietaryConstraints, Macros) values (663, 'Lamb - Loin, Trimmed, Boneless', 981, 'Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros. Vestibulum ac est lacinia nisi venenatis tristique. Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue.', 86, 282, 3, 704);
insert into Meals (MealID, MealName, ServedAt, Description, Votes, Allergen, DietaryConstraints, Macros) values (665, 'Lettuce - Iceberg', 884, 'Phasellus sit amet erat.', 247, 285, 5, 990);
insert into Meals (MealID, MealName, ServedAt, Description, Votes, Allergen, DietaryConstraints, Macros) values (320, 'Soup - Campbells Chili', 382, 'Morbi porttitor lorem id ligula. Suspendisse ornare consequat lectus. In est risus, auctor sed, tristique in, tempus sit amet, sem.', 82, 199, 3, 277);
insert into Meals (MealID, MealName, ServedAt, Description, Votes, Allergen, DietaryConstraints, Macros) values (837, 'Lid - 10,12,16 Oz', 551, 'Cras non velit nec nisi vulputate nonummy.', 111, 428, 4, 565);
insert into Meals (MealID, MealName, ServedAt, Description, Votes, Allergen, DietaryConstraints, Macros) values (926, 'Wine - Cave Springs Dry Riesling', 520, 'Ut tellus. Nulla ut erat id mauris vulputate elementum. Nullam varius.', 122, 566, 4, 187);
insert into Meals (MealID, MealName, ServedAt, Description, Votes, Allergen, DietaryConstraints, Macros) values (724, 'Pasta - Ravioli', 880, 'In blandit ultrices enim. Lorem ipsum dolor sit amet, consectetuer adipiscing elit.', 16, 531, 1, 670);
insert into Meals (MealID, MealName, ServedAt, Description, Votes, Allergen, DietaryConstraints, Macros) values (434, 'Wine - Saint - Bris 2002, Sauv', 695, 'Duis bibendum.', 47, 360, 4, 127);
insert into Meals (MealID, MealName, ServedAt, Description, Votes, Allergen, DietaryConstraints, Macros) values (329, 'Peppercorns - Green', 980, 'Nullam molestie nibh in lectus.', 31, 479, 5, 867);
insert into Meals (MealID, MealName, ServedAt, Description, Votes, Allergen, DietaryConstraints, Macros) values (911, 'Tart Shells - Barquettes, Savory', 261, 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Proin interdum mauris non ligula pellentesque ultrices. Phasellus id sapien in sapien iaculis congue.', 77, 750, 3, 153);
insert into Meals (MealID, MealName, ServedAt, Description, Votes, Allergen, DietaryConstraints, Macros) values (927, 'Puree - Mango', 721, 'Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo.', 126, 417, 2, 328);
insert into Meals (MealID, MealName, ServedAt, Description, Votes, Allergen, DietaryConstraints, Macros) values (394, 'Barramundi', 518, 'Nam nulla. Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede. Morbi porttitor lorem id ligula.', 194, 119, 1, 550);
insert into Meals (MealID, MealName, ServedAt, Description, Votes, Allergen, DietaryConstraints, Macros) values (600, 'Pork Ham Prager', 580, 'In congue. Etiam justo.', 47, 390, 5, 703);
insert into Meals (MealID, MealName, ServedAt, Description, Votes, Allergen, DietaryConstraints, Macros) values (585, 'Bread - Italian Sesame Poly', 622, 'Integer ac leo. Pellentesque ultrices mattis odio. Donec vitae nisi.', 91, 946, 5, 333);
insert into Meals (MealID, MealName, ServedAt, Description, Votes, Allergen, DietaryConstraints, Macros) values (297, 'Dasheen', 901, 'Aliquam non mauris. Morbi non lectus. Aliquam sit amet diam in magna bibendum imperdiet.', 284, 343, 3, 738);
insert into Meals (MealID, MealName, ServedAt, Description, Votes, Allergen, DietaryConstraints, Macros) values (383, 'Bread Base - Toscano', 694, 'Etiam justo. Etiam pretium iaculis justo.', 10, 264, 1, 136);
insert into Meals (MealID, MealName, ServedAt, Description, Votes, Allergen, DietaryConstraints, Macros) values (409, 'Carbonated Water - White Grape', 297, 'Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem. Integer tincidunt ante vel ipsum.', 115, 404, 1, 425);
insert into Meals (MealID, MealName, ServedAt, Description, Votes, Allergen, DietaryConstraints, Macros) values (718, 'Beer - Blue', 933, 'Praesent blandit lacinia erat.', 219, 893, 1, 970);
insert into Meals (MealID, MealName, ServedAt, Description, Votes, Allergen, DietaryConstraints, Macros) values (519, 'Sauce - Vodka Blush', 480, 'Mauris sit amet eros. Suspendisse accumsan tortor quis turpis.', 201, 440, 5, 486);
insert into Meals (MealID, MealName, ServedAt, Description, Votes, Allergen, DietaryConstraints, Macros) values (621, 'Coffee Cup 8oz 5338cd', 150, 'Nullam porttitor lacus at turpis. Donec posuere metus vitae ipsum.', 171, 711, 4, 743);
insert into Meals (MealID, MealName, ServedAt, Description, Votes, Allergen, DietaryConstraints, Macros) values (211, 'Lamb - Pieces, Diced', 707, 'Morbi vel lectus in quam fringilla rhoncus. Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis.', 35, 802, 2, 306);
insert into Meals (MealID, MealName, ServedAt, Description, Votes, Allergen, DietaryConstraints, Macros) values (868, 'Foam Tray S2', 570, 'Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Etiam vel augue.', 28, 940, 4, 478);
insert into Meals (MealID, MealName, ServedAt, Description, Votes, Allergen, DietaryConstraints, Macros) values (435, 'Maple Syrup', 685, 'Donec ut mauris eget massa tempor convallis.', 132, 832, 3, 536);
