CREATE TABLE IF NOT EXISTS Vendors (
    VendorID INTEGER,
    VendorName TEXT,
    Address VARCHAR(99),
    PRIMARY KEY (VendorID)
);
insert into Vendors (VendorID, VendorName, Address) values (798, 'Vandervort, Parisian and Barrows', '1 Independence Junction');
insert into Vendors (VendorID, VendorName, Address) values (619, 'Thompson LLC', '46424 Thierer Plaza');
insert into Vendors (VendorID, VendorName, Address) values (471, 'Schumm-Veum', '2621 Pennsylvania Point');
insert into Vendors (VendorID, VendorName, Address) values (904, 'Wuckert Group', '8259 Fairview Place');
insert into Vendors (VendorID, VendorName, Address) values (730, 'Boehm Inc', '6 Bartillon Lane');
insert into Vendors (VendorID, VendorName, Address) values (621, 'Ledner and Sons', '9 Red Cloud Crossing');
insert into Vendors (VendorID, VendorName, Address) values (948, 'Beatty Inc', '12208 2nd Alley');
insert into Vendors (VendorID, VendorName, Address) values (789, 'Effertz Inc', '078 Hazelcrest Court');
insert into Vendors (VendorID, VendorName, Address) values (189, 'Walter, Moen and VonRueden', '0696 Westend Junction');
insert into Vendors (VendorID, VendorName, Address) values (305, 'Schulist-Bednar', '707 Hoard Plaza');
insert into Vendors (VendorID, VendorName, Address) values (715, 'McClure-Cormier', '771 Erie Drive');
insert into Vendors (VendorID, VendorName, Address) values (105, 'Roob, Runte and Breitenberg', '365 Gina Crossing');
insert into Vendors (VendorID, VendorName, Address) values (355, 'Muller, Yost and Stokes', '1308 Pennsylvania Center');
insert into Vendors (VendorID, VendorName, Address) values (938, 'Ziemann LLC', '925 Sage Place');
insert into Vendors (VendorID, VendorName, Address) values (129, 'Collins, Bins and Koepp', '4511 Packers Crossing');
insert into Vendors (VendorID, VendorName, Address) values (419, 'Weissnat, Mosciski and McCullough', '55896 Duke Alley');
insert into Vendors (VendorID, VendorName, Address) values (375, 'Kilback LLC', '09941 Vera Alley');
insert into Vendors (VendorID, VendorName, Address) values (200, 'Satterfield-Baumbach', '60 Elgar Hill');
insert into Vendors (VendorID, VendorName, Address) values (814, 'Vandervort, Murray and Batz', '2560 Jenifer Alley');
insert into Vendors (VendorID, VendorName, Address) values (326, 'Botsford Group', '64412 1st Circle');
insert into Vendors (VendorID, VendorName, Address) values (784, 'Daniel-Heathcote', '6348 Harbort Terrace');
insert into Vendors (VendorID, VendorName, Address) values (970, 'Buckridge-Nienow', '5 Division Hill');
insert into Vendors (VendorID, VendorName, Address) values (582, 'Hudson, Barton and Renner', '81 Sloan Parkway');
insert into Vendors (VendorID, VendorName, Address) values (662, 'Zemlak, Schinner and Wuckert', '7838 Memorial Point');
insert into Vendors (VendorID, VendorName, Address) values (324, 'Bergstrom Group', '97194 Gulseth Center');
insert into Vendors (VendorID, VendorName, Address) values (307, 'West-Kshlerin', '397 Corscot Center');
insert into Vendors (VendorID, VendorName, Address) values (533, 'D''Amore, Klein and Barrows', '119 Thierer Parkway');
insert into Vendors (VendorID, VendorName, Address) values (127, 'Stamm Inc', '05 High Crossing Place');
insert into Vendors (VendorID, VendorName, Address) values (407, 'Roberts Inc', '9426 Acker Court');
insert into Vendors (VendorID, VendorName, Address) values (567, 'Reynolds Group', '5 Hallows Place');
insert into Vendors (VendorID, VendorName, Address) values (913, 'Koch and Sons', '4 Ryan Way');
insert into Vendors (VendorID, VendorName, Address) values (925, 'Fahey, Kiehn and Bayer', '7131 Montana Park');
insert into Vendors (VendorID, VendorName, Address) values (185, 'Barton, Cruickshank and Kessler', '26866 Vermont Circle');
insert into Vendors (VendorID, VendorName, Address) values (687, 'Bode and Sons', '35673 American Ash Lane');
insert into Vendors (VendorID, VendorName, Address) values (767, 'Altenwerth-Harris', '9 Lakeland Plaza');
insert into Vendors (VendorID, VendorName, Address) values (134, 'Kihn-Schowalter', '28 Petterle Place');
insert into Vendors (VendorID, VendorName, Address) values (511, 'Kuphal, Lakin and Goodwin', '6 Lotheville Hill');
insert into Vendors (VendorID, VendorName, Address) values (207, 'Veum, Glover and Tromp', '4 Blue Bill Park Park');
insert into Vendors (VendorID, VendorName, Address) values (207, 'Krajcik, Wisoky and Wisozk', '71844 Forest Run Point');
insert into Vendors (VendorID, VendorName, Address) values (991, 'Gusikowski, Heaney and Stoltenberg', '7 Kropf Point');
insert into Vendors (VendorID, VendorName, Address) values (653, 'Fadel and Sons', '63 Duke Circle');
insert into Vendors (VendorID, VendorName, Address) values (894, 'Smitham and Sons', '356 Dapin Circle');
insert into Vendors (VendorID, VendorName, Address) values (159, 'Jacobs-Harber', '8317 Lunder Pass');
insert into Vendors (VendorID, VendorName, Address) values (820, 'Orn LLC', '85063 Northland Center');
insert into Vendors (VendorID, VendorName, Address) values (596, 'Mueller, Bashirian and Hamill', '77 Dakota Crossing');
insert into Vendors (VendorID, VendorName, Address) values (381, 'Kling, Waelchi and Thiel', '7267 Continental Terrace');
insert into Vendors (VendorID, VendorName, Address) values (851, 'Bailey-Steuber', '3263 Melody Center');
insert into Vendors (VendorID, VendorName, Address) values (371, 'Gibson, Bartell and Paucek', '998 Raven Road');
insert into Vendors (VendorID, VendorName, Address) values (882, 'Corwin-Kulas', '63 Scoville Park');
insert into Vendors (VendorID, VendorName, Address) values (944, 'Hagenes LLC', '5546 Sutherland Circle');
insert into Vendors (VendorID, VendorName, Address) values (938, 'Conroy, Rutherford and Borer', '99341 Drewry Point');
insert into Vendors (VendorID, VendorName, Address) values (637, 'Ernser, Crooks and Bailey', '2538 Golden Leaf Trail');
insert into Vendors (VendorID, VendorName, Address) values (658, 'O''Hara, Shanahan and Beahan', '9 Clemons Lane');
insert into Vendors (VendorID, VendorName, Address) values (132, 'Homenick-Rosenbaum', '82 Carey Trail');
insert into Vendors (VendorID, VendorName, Address) values (555, 'VonRueden Group', '12409 Evergreen Street');
insert into Vendors (VendorID, VendorName, Address) values (764, 'Wisozk, Effertz and Schimmel', '2099 Scofield Avenue');
insert into Vendors (VendorID, VendorName, Address) values (270, 'Koelpin, Dach and Hettinger', '465 Grasskamp Center');
insert into Vendors (VendorID, VendorName, Address) values (753, 'Ernser LLC', '538 Leroy Parkway');
insert into Vendors (VendorID, VendorName, Address) values (988, 'Miller Group', '0 Vermont Plaza');
insert into Vendors (VendorID, VendorName, Address) values (459, 'Weissnat, Schmeler and Paucek', '79 Messerschmidt Plaza');
insert into Vendors (VendorID, VendorName, Address) values (748, 'Strosin LLC', '1 Monterey Parkway');
insert into Vendors (VendorID, VendorName, Address) values (971, 'Mann, Morar and Metz', '55 Arizona Avenue');
insert into Vendors (VendorID, VendorName, Address) values (109, 'Howell, Howell and Mills', '491 Summer Ridge Parkway');
insert into Vendors (VendorID, VendorName, Address) values (293, 'Bernhard, Fay and Osinski', '75 Johnson Drive');
insert into Vendors (VendorID, VendorName, Address) values (458, 'Schoen-Farrell', '82428 Sheridan Trail');
insert into Vendors (VendorID, VendorName, Address) values (764, 'Hayes-Johnson', '31863 Waxwing Crossing');
insert into Vendors (VendorID, VendorName, Address) values (579, 'Lebsack-Littel', '03 Riverside Lane');
insert into Vendors (VendorID, VendorName, Address) values (643, 'Osinski-O''Kon', '929 Golf Course Court');
insert into Vendors (VendorID, VendorName, Address) values (641, 'Stracke-Grady', '37876 Glacier Hill Road');
insert into Vendors (VendorID, VendorName, Address) values (829, 'Parker, Koss and O''Reilly', '6 Merrick Lane');
insert into Vendors (VendorID, VendorName, Address) values (287, 'Rolfson-Deckow', '7823 Namekagon Way');
insert into Vendors (VendorID, VendorName, Address) values (206, 'Waters, Monahan and Hahn', '34647 Bashford Place');
insert into Vendors (VendorID, VendorName, Address) values (452, 'Rippin-Johns', '1 Division Alley');
insert into Vendors (VendorID, VendorName, Address) values (729, 'Walsh Group', '52 Melody Terrace');
insert into Vendors (VendorID, VendorName, Address) values (468, 'Goyette-Barrows', '07899 Hoard Center');
insert into Vendors (VendorID, VendorName, Address) values (273, 'Streich, Stroman and Luettgen', '0007 Karstens Plaza');
insert into Vendors (VendorID, VendorName, Address) values (398, 'Lebsack-Huel', '609 Bluestem Avenue');
insert into Vendors (VendorID, VendorName, Address) values (395, 'Douglas Inc', '07713 Namekagon Park');
insert into Vendors (VendorID, VendorName, Address) values (147, 'Williamson, VonRueden and Jacobson', '7970 Gateway Alley');
insert into Vendors (VendorID, VendorName, Address) values (291, 'O''Kon-Durgan', '7 Meadow Vale Road');
insert into Vendors (VendorID, VendorName, Address) values (261, 'Ankunding Inc', '7 Truax Trail');
insert into Vendors (VendorID, VendorName, Address) values (631, 'King-Hayes', '28 Dayton Parkway');
insert into Vendors (VendorID, VendorName, Address) values (571, 'Homenick-Leannon', '64 Northwestern Terrace');
insert into Vendors (VendorID, VendorName, Address) values (403, 'Mertz and Sons', '291 Spenser Center');
insert into Vendors (VendorID, VendorName, Address) values (240, 'Smitham LLC', '76589 Ridge Oak Hill');
insert into Vendors (VendorID, VendorName, Address) values (979, 'Swaniawski LLC', '1 Monterey Avenue');
insert into Vendors (VendorID, VendorName, Address) values (867, 'McKenzie Inc', '397 Victoria Court');
insert into Vendors (VendorID, VendorName, Address) values (134, 'Bosco-Bashirian', '4 Hudson Crossing');
insert into Vendors (VendorID, VendorName, Address) values (387, 'Moore, Carroll and White', '7804 Packers Road');
insert into Vendors (VendorID, VendorName, Address) values (780, 'Kiehn Group', '0 Londonderry Road');
